source 'https://rubygems.org'

# ruby '1.9.3'

gem 'locomotivecms_builder', '~> 1.0.0.rc1'

group :development do
  # Mac OS X
  gem 'rb-fsevent', '~> 0.9.1', :require => RUBY_PLATFORM.include?('darwin') && 'rb-fsevent'

  # TODO: Linux

  # TODO: Windows
end

group :misc do
  # Add your extra gems here
  # gem 'susy', require: 'susy'
  # gem 'redcarpet', require: 'redcarpet'
end