# gem 'locomotive_builder', require: true

# DEV
gem 'locomotivecms_mounter', '~> 1.0.0.rc1'
gem 'locomotivecms_builder', '~> 1.0.0.rc1'

# Mac OS X
gem 'rb-fsevent', '~> 0.9.1'

# Linux
# TODO

# Windows
# TODO

# add your other gems here

